server:
  port: 8088
spring:
  banner:
    location: classpath:bannner.tx
  main:
    banner-mode: console
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/DB_EXAMINATION?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: debug
  config: classpath:log4j2.xml
